parameters:
    character.characteritem.class: Game\CharacterBundle\Manager\CharacterItemManager
    character.characteritem.entity: Game\CharacterBundle\Entity\CharacterItem
    character.character.class: Game\CharacterBundle\Manager\CharacterManager
    character.character.entity: Game\CharacterBundle\Entity\Character
    character.character_restore_listener.class: Game\CharacterBundle\EventListener\CharacterRestoreListener
    character.character_shop_listener.class: Game\CharacterBundle\EventListener\CharacterShopListener

services:
    character.characteritem_manager:
        class: %character.characteritem.class%
        arguments: [%character.characteritem.entity%]
        parent: core.core_manager
        calls:
            - [ setWeaponManager, [ @item.weapon_manager ] ]


    character.character_manager:
        class: %character.character.class%
        arguments: [%character.character.entity%]
        parent: core.core_manager

    character.character_restore.listener:
        class: %character.character_restore_listener.class%
        tags:
            - { name: kernel.event_listener, event: character.travel, method: onCharacterTravel }
            - { name: kernel.event_listener, event: character.rest, method: onCharacterRest }

    character.character_shop.listener:
        class: %character.character_shop_listener.class%
        tags:
            - { name: kernel.event_listener, event: character.buy, method: onCharacterBuy}
            - { name: kernel.event_listener, event: character.sell, method: onCharacterSell}