services:
    core.core_manager:
        abstract:  true
        class: Game\CoreBundle\Manager\CoreManager
        calls:
            - [ setEntityProperties, [ @doctrine.orm.entity_manager ] ]

    core.roll_manager:
        class: Game\CoreBundle\Manager\RollManager