imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:     ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FosUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Game\UserBundle\Entity\User

# FosComment
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Game\CommentBundle\Entity\Comment
            thread: Game\CommentBundle\Entity\Thread
    acl_roles:
        comment:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

# HWIO
hwi_oauth:
    connect:
        account_connector: user.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            twitter: twitter_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           284314515082984
            client_secret:       bc26de934b5092ae5daebba7eb310d1a
#            scope: ""
#            options:
#                display: popup
        twitter:
            type:                twitter
            client_id:           lXGWpekcDtljep0pMml4iayQw
            client_secret:       oNO7dnF4UNxoAogdvOUti2qNzlM4QKWe1UsgHPkzf1tFZOmM1p

# liipImagine
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        portrait_mini:
            quality: 75
            filters:
                thumbnail: { size: [22, 34], mode: outbound }
        portrait_medium:
            quality: 75
            filters:
                thumbnail: { size: [110, 170],  mode: outbound }
        quest_medium:
            quality: 75
            filters:
                thumbnail: { size: [320, 160], mode: outbound }