game_shop:
    resource: "@GameShopBundle/Controller/DefaultController.php"
    prefix:   /shop
    type:     annotation

game_ui:
    resource: "@GameUIBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

game_character_inventory:
    resource: "@GameCharacterBundle/Controller/InventoryController.php"
    prefix:   /character/inventory
    type:     annotation
game_npc:
    resource: "@NpcBundle/Controller/"
    type:     annotation
    prefix:   /

game_map_travel:
    resource: "@GameMapBundle/Controller/TravelController.php"
    prefix:   /map/travel
    type:     annotation

game_map:
    resource: "@GameMapBundle/Controller/DefaultController.php"
    prefix:   /map
    type:     annotation