game_shop:
    resource: "@ShopBundle/Controller/DefaultController.php"
    prefix:   /shop
    type:     annotation

game_ui:
    resource: "@UIBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

game_character_inventory:
    resource: "@CharacterBundle/Controller/InventoryController.php"
    prefix:   /character/inventory
    type:     annotation

game_map_travel:
    resource: "@MapBundle/Controller/TravelController.php"
    prefix:   /map/travel
    type:     annotation

game_map:
    resource: "@MapBundle/Controller/MapController.php"
    prefix:   /map
    type:     annotation