game_ui:
    resource: "@GameUIBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

game_map_travel:
    resource: "@GameMapBundle/Controller/TravelController.php"
    prefix:   /map/travel
    type:     annotation

game_map:
    resource: "@GameMapBundle/Controller/DefaultController.php"
    prefix:   /map
    type:     annotation