game_shop:
    resource: "@ShopBundle/Controller/DefaultController.php"
    prefix:   /shop
    type:     annotation

game_ui:
    resource: "@UIBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

game_character:
    resource: "@CharacterBundle/Controller/CharacterController.php"
    prefix:   /character
    type:     annotation

game_character_lvlup:
    resource: "@CharacterBundle/Controller/LevelUpController.php"
    prefix:   /character/level-up
    type:     annotation

game_character_roster:
    resource: "@CharacterBundle/Controller/RosterController.php"
    prefix:   /character/roster
    type:     annotation

game_character_inventory:
    resource: "@CharacterBundle/Controller/InventoryController.php"
    prefix:   /character/inventory
    type:     annotation

game_map_travel:
    resource: "@MapBundle/Controller/TravelController.php"
    prefix:   /map/travel
    type:     annotation

game_map:
    resource: "@MapBundle/Controller/MapController.php"
    prefix:   /map
    type:     annotation

game_battle:
    resource: "@BattleBundle/Controller/BattleController.php"
    prefix:   /battle
    type:     annotation


## FOSUser ##

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile