parameters:
    game.game.class: Game\GameBundle\Manager\GameManager
    game.game.entity: Game\GameBundle\Entity\Game
    game.boss.class: Game\GameBundle\Manager\BossManager
    game.boss.entity: Game\GameBundle\Entity\Boss
    game.raid.class: Game\GameBundle\Manager\RaidManager
    game.raid.entity: Game\GameBundle\Entity\Raid
    game.gamecreator.class: Game\GameBundle\Manager\GameCreatorManager

services:
    game.game_manager:
        class: %game.game.class%
        arguments: [%game.game.entity%]
        parent: core.core_manager
        calls:
            - [ setRollManager, [ @core.roll_manager ] ]

    game.boss_manager:
        class: %game.boss.class%
        arguments: [%game.boss.entity%]
        parent: core.core_manager
        calls:
            - [ setRollManager, [ @core.roll_manager ] ]

    game.raid_manager:
        class: %game.raid.class%
        arguments: [%game.raid.entity%]
        parent: core.core_manager
        calls:
            - [ setRollManager, [ @core.roll_manager ] ]

    game.twig.boss_extension:
        class: Game\GameBundle\Twig\BossExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setBossManager, [ @game.boss_manager ] ]
            - [ setGameManager, [ @game.game_manager ] ]
            - [ setRaidManager, [ @game.raid_manager ] ]

    game.gamecreator_manager:
        class: %game.gamecreator.class%
        arguments: [%game.game.entity%]
        parent: core.core_manager
        calls:
            - [ setRollManager, [ @core.roll_manager ] ]
            - [ setMonsterManager, [ @monster.monster_manager ] ]
            - [ setItemManager, [ @item.item_manager ] ]