parameters:
    notification.notification.class: Game\NotificationBundle\Manager\NotificationManager
    notification.notification.entity: Game\NotificationBundle\Entity\Notification

services:
    notification.notification_manager:
        class: %notification.notification.class%
        arguments: [%notification.notification.entity%]
        parent: core.core_manager