parameters:
  game.battle.class: Game\BattleBundle\Manager\BattleManager
  game.battle.entity_class: Game\BattleBundle\Entity\Battle
  game.battleresolver.class: Game\BattleBundle\Manager\BattleResolver

services:
  battle.battle_manager:
    class: %game.battle.class%
    arguments: [%game.battle.entity_class%]
    parent: core.core_manager
    calls:
      - [ setBattleResolver, [ @battle.battleresolver ] ]

  battle.battleresolver:
    class: %game.battleresolver.class%
    calls:
      - [ setRollManager, [ @core.roll_manager ] ]
      - [ setCharacterManager, [ @character.character_manager ] ]
      - [ setEventDispatcher, [ @event_dispatcher ] ]
      - [ setXPManager, [ @character.xp_manager ] ]