parameters:
    user.user.class: Game\UserBundle\Manager\UserManager
    user.user.entity: Game\UserBundle\Entity\User

services:
    user.user_manager:
        class: %user.user.class%
        arguments: [%user.user.entity%]
        parent: core.core_manager
        calls:
            - [ setSecurityContext, [ @security.context ] ]
            - [ setFOSUserManager, [ @fos_user.user_manager ] ]
            - [ setSession, [ @session ] ]
            - [ setCharacterManager, [ @character.character_manager ] ]