parameters:
  game.monster.class: Game\MonsterBundle\Manager\MonsterManager
  game.monster.entity_class: Game\MonsterBundle\Entity\Monster
  game.spawn.class: Game\MonsterBundle\Manager\SpawnManager
  game.spawn.entity_class: Game\MonsterBundle\Entity\Spawn
  game.race.class: Game\MonsterBundle\Manager\RaceManager
  game.race.entity_class: Game\MonsterBundle\Entity\Race
  game.loot.class: Game\MonsterBundle\Manager\LootManager
  game.loottable.entity_class: Game\MonsterBundle\Entity\LootTable

services:
  monster.monster_manager:
      class: %game.monster.class%
      arguments: [%game.monster.entity_class%]
      parent: core.core_manager
      calls:
          - [ setRollManager, [ @core.roll_manager ] ]

  monster.spawn_manager:
      class: %game.spawn.class%
      arguments: [%game.spawn.entity_class%]
      parent: core.core_manager
      calls:
          - [ setRollManager, [ @core.roll_manager ] ]

  monster.race_manager:
      class: %game.race.class%
      arguments: [%game.race.entity_class%]
      parent: core.core_manager

  monster.loot_manager:
      class: %game.loot.class%
      arguments: [%game.loottable.entity_class%]
      parent: core.core_manager
      calls:
          - [ setRollManager, [ @core.roll_manager ] ]